{% set name = "iminuit" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a08ad17fa6876ec91ea845cc9222b7a1bc6e7bafa31a4fd962632759b3aa2306

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  commands:
    - python -c "import iminuit, sys; sys.exit(iminuit.test())"

about:
  home: https://github.com/scikit-hep/iminuit
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Interactive Minimization Tools based on MINUIT
  description: |
    iminuit is designed from ground up to be fast, interactive and cython
    friendly. iminuit extract function signature very permissively starting
    from checking func_code down to last resort of parsing docstring (or you
    could tell iminuit to stop looking and take your answer). The interface is
    inspired heavily by PyMinuit and the status printout is inspired by ROOT
    Minuit. iminuit is mostly compatible with PyMinuit (with few exceptions).
    Existing PyMinuit code can be ported to iminuit by just changing the
    import statement.
  doc_url: http://iminuit.readthedocs.io
  dev_url: https://github.com/scikit-hep/iminuit

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - piti118
    - HDembinski
    - beckermr
    - chrisburr
    - henryiii
