schema_version: 1

context:
  name: iminuit
  version: "2.31.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d5e004f1ffd83d2a076409fbf4a79691e7a17c9d73950bb63465af32e104de18

build:
  number: 1
  skip: match(python, "<3.9")
  script:
    - if: unix
      then: export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}
    - if: win
      then: set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake >=3.15
    - if: unix
      then: make
  host:
    - python
    - pip
    - scikit-build-core
    - pybind11
  run:
    - python
    - ${{ pin_compatible('numpy') }}
    - if: match(python, "<3.9")
      then: typing_extensions

tests:
  - python:
      imports:
        - iminuit
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - pip
    script:
      - python -m pytest tests
      - pip check

about:
  license: LGPL-2.0-or-later
  license_file: LICENSE
  summary: Interactive Minimization Tools based on MINUIT
  description: |
    iminuit is designed from ground up to be fast, interactive and cython
    friendly. iminuit extract function signature very permissively starting
    from checking func_code down to last resort of parsing docstring (or you
    could tell iminuit to stop looking and take your answer). The interface is
    inspired heavily by PyMinuit and the status printout is inspired by ROOT
    Minuit. iminuit is mostly compatible with PyMinuit (with few exceptions).
    Existing PyMinuit code can be ported to iminuit by just changing the
    import statement.
  homepage: https://github.com/scikit-hep/iminuit
  repository: https://github.com/scikit-hep/iminuit
  documentation: http://iminuit.readthedocs.io

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - HDembinski
    - chrisburr
    - henryiii
