# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vY4syjNqqnjL4tGQTZkzjoMizUpWwdQIl4XF2wq5Ia4ftJIZtUm+BgybhBY+2gyvRRrLm/gLkVBGdzpatjCZKjqMg/YAHmJp0BwNB+7pAKe0/Z3sBcK742DQVoiJIQzh7vYOtct1G4baKccUQ9tJI+ASEytnd/+4d2Hj17AVY/oldy8OEHkDp6u9dRSKflgJqZ5T9Y5tJBQYm8t/rB6lWTTPM+hFZVB10Gm5lKlvzn8+YOGrCUmoD6gou5Rc1jgFeJz8kyLoYSpeOrewL/b6wFZVud3mjkkNRFphhjbYMJ4iwJnzLRGHQNDn1Dr4UoYvI3No6rXjtbLHxL5nCtDF8oxT/mUjMCb8qdSlN1b5LLWQW3Ub5LdXLnxXn+m5dkQYBU1+DutcmJ8H1HqBYq12n0ejY69l2pu27kWl6w0rVCQl5jZrCC2Qk5XvyOMLa4rhoeptUHD2h43KUAztA21j2Cpiakd70r63JT6vA1YkwgRZZ8AwOgb+pAo/MM+S7oyg6nQClooEDbsrFC5vYksrPIYEfrbTr0Et5Tfp+9j7Lh7qpJRKQoKkJork5NISh4LVWiR8XqKiRnV3EW0kMRthW/bdI0/EnH0pdg/RPx2RiXX860LszpeA71jDoMjP19Qc6qna+tHiyLUq9E/SvGEUJBd5ArMFL7bQFpHRqFFYDeY="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python3.6 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_python3.7 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_python3.8 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi