# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vY4syjNqqnjL4tGQTZkzjoMizUpWwdQIl4XF2wq5Ia4ftJIZtUm+BgybhBY+2gyvRRrLm/gLkVBGdzpatjCZKjqMg/YAHmJp0BwNB+7pAKe0/Z3sBcK742DQVoiJIQzh7vYOtct1G4baKccUQ9tJI+ASEytnd/+4d2Hj17AVY/oldy8OEHkDp6u9dRSKflgJqZ5T9Y5tJBQYm8t/rB6lWTTPM+hFZVB10Gm5lKlvzn8+YOGrCUmoD6gou5Rc1jgFeJz8kyLoYSpeOrewL/b6wFZVud3mjkkNRFphhjbYMJ4iwJnzLRGHQNDn1Dr4UoYvI3No6rXjtbLHxL5nCtDF8oxT/mUjMCb8qdSlN1b5LLWQW3Ub5LdXLnxXn+m5dkQYBU1+DutcmJ8H1HqBYq12n0ejY69l2pu27kWl6w0rVCQl5jZrCC2Qk5XvyOMLa4rhoeptUHD2h43KUAztA21j2Cpiakd70r63JT6vA1YkwgRZZ8AwOgb+pAo/MM+S7oyg6nQClooEDbsrFC5vYksrPIYEfrbTr0Et5Tfp+9j7Lh7qpJRKQoKkJork5NISh4LVWiR8XqKiRnV3EW0kMRthW/bdI0/EnH0pdg/RPx2RiXX860LszpeA71jDoMjP19Qc6qna+tHiyLUq9E/SvGEUJBd5ArMFL7bQFpHRqFFYDeY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
