appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: vY4syjNqqnjL4tGQTZkzjoMizUpWwdQIl4XF2wq5Ia4ftJIZtUm+BgybhBY+2gyvRRrLm/gLkVBGdzpatjCZKjqMg/YAHmJp0BwNB+7pAKe0/Z3sBcK742DQVoiJIQzh7vYOtct1G4baKccUQ9tJI+ASEytnd/+4d2Hj17AVY/oldy8OEHkDp6u9dRSKflgJqZ5T9Y5tJBQYm8t/rB6lWTTPM+hFZVB10Gm5lKlvzn8+YOGrCUmoD6gou5Rc1jgFeJz8kyLoYSpeOrewL/b6wFZVud3mjkkNRFphhjbYMJ4iwJnzLRGHQNDn1Dr4UoYvI3No6rXjtbLHxL5nCtDF8oxT/mUjMCb8qdSlN1b5LLWQW3Ub5LdXLnxXn+m5dkQYBU1+DutcmJ8H1HqBYq12n0ejY69l2pu27kWl6w0rVCQl5jZrCC2Qk5XvyOMLa4rhoeptUHD2h43KUAztA21j2Cpiakd70r63JT6vA1YkwgRZZ8AwOgb+pAo/MM+S7oyg6nQClooEDbsrFC5vYksrPIYEfrbTr0Et5Tfp+9j7Lh7qpJRKQoKkJork5NISh4LVWiR8XqKiRnV3EW0kMRthW/bdI0/EnH0pdg/RPx2RiXX860LszpeA71jDoMjP19Qc6qna+tHiyLUq9E/SvGEUJBd5ArMFL7bQFpHRqFFYDeY=}
conda_forge_output_validation: true
bot:
  automerge: true
